from operation_investigation_library_israeldavidvm.metodoGrafico import *
from operation_investigation_library_israeldavidvm.metodoSimplex import *
from operation_investigation_library_israeldavidvm.pert_cpm import *
